### ISSUE TITLE
Incompatible with node <7 (due to use of Object.entries)

### ISSUE THREAD

**Issue by lenntt** [wswebcreation/wdio-multiple-cucumber-html-reporter#13]
**Environment (please complete the following information):**
 - Node.js version: 6.11.5
 - NPM version: 6.3.0
 - webdriver.io version: .13.2
 - wdio-cucumber-framework version: 2.2.7
 - wdio-multiple-cucumber-html-reporter version: 0.3.2

**Config of webdriver.io and the reporter**
a bare setup.

**Describe the bug**
Experimenting with webdriver.io, cucumber and of course, my favorite html reporter.
webdriver.io runs fine with node6, but this plugin seems to throw:

```
TypeError: Object.entries is not a function
    at generateJson (/Users/lennart/dev/github/ba-webdriverio/node_modules/wdio-multiple-cucumber-html-reporter/build/generateJson.js:27:12)
    at MultipleCucumberHtmlReporter.onEnd (/Users/lennart/dev/github/ba-webdriverio/node_modules/wdio-multiple-cucumber-html-reporter/build/reporter.js:157:44)
```

Seems `Object.entries` was only introduced in node >=7
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**To Reproduce**
Run an empty webdriver.io project with cucumber and this plugin in node 6

**Expected behavior**
no errors, a fancy html report :)

**Snapshots**

**Additional context**
Suggested, either:
- clear requirements on the readme
- support node6 (by iterating over the object keys instead, or using babel?)

**Comment by wswebcreation** [comment]
> Expected behavior no errors, a fancy html report :)

![season-20-the-simpsons-20x11-l2JdTfuwCLvwFBb0I](https://media1.giphy.com/media/l2JdTfuwCLvwFBb0I/giphy.gif?cid=e1bb72ff5bbf8fea586e67436b603f18)

Will update the the docs, thanks for the headsup. I got rewriting on my todo-list, but I'm currently busy with a different module

**Comment by lenntt** [comment]
Not sure if I have enough time on my hands, but would you accept a PR to fix node 6 compatibility?

**Comment by wswebcreation** [comment]
That would be nice but on the other hand only for 6 months because support will stop in April 2019

**Comment by wswebcreation** [comment]
I'm going to close this for now, due to the support of NodeJS 6 will stop in April
