### ISSUE TITLE
WebdriverIO errors out when feature has no defined steps

### ISSUE THREAD

**Issue by Rob-Meijeren** [wswebcreation/wdio-multiple-cucumber-html-reporter#16]
**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1]: v8.12.0
 - NPM version: [e.g. 5.8.0]: v6.4.1
 - webdriver.io version: [e.g. 4.13.1]: ^4.14.0
 - wdio-cucumber-framework version: [e.g. 2.2.0 (if lower this module will not work as it should be)]: ^2.2.8
 - wdio-multiple-cucumber-html-reporter version: [e.g. 0.1.3]: ^0.3.2

**Config of webdriver.io and the reporter**
An example of how you configured the reporter in your webdriver.io config

```js
reporters: ['dot','multiple-cucumber-html'],
    reporterOptions: {
      htmlReporter: {
          jsonFolder: './e2e/tmp',
          reportFolder: `./e2e/report`,
          removeFolders: true,
          pageTitle: '',
          reportName: '',
          displayDuration: true,
          disableLog: true
      }
    },
```
**Describe the bug**

When running webdriver and a feature has all scenario ignored and the steps of the scenarios are undefined the reporter gives an error that it can't save an screenshot and that it can't read steps of undefined (reporter.js line 290 (compiled version)). this is because its trying to access _elements of the results which isn't defined as the feature/scenario doesn't have any.

Note this doesn't always happen for some reason but it results in webdriver erroring out with a channel closed exception leaving the process in the terminal running but nothing is being executed.

**To Reproduce**

create features with scenarios that have undefined steps and add a ignore tag to the scenarios. In the cucumberOpts set the tagExpression to 'not @ignore' and start running. I had 17 features myself with multiple scenarios in each feature.

[Include code or an example repository that can easily be set up]

**Expected behavior**

that the errors of _elements not being present is catched

**Snapshots**
If applicable, add snapshots to help explain your problem.

**Additional context**

**Comment by wswebcreation** [comment]
@Rob-Meijeren 
Sorry for my late reaction. Been very busy lately, will check it this week

**Comment by Rob-Meijeren** [comment]
Hi Wim, Sorry for the delay as I was on Holiday. After some more deepdiving it turns out that it happens when webdriverio fails to take a screenshot. So when it says in the command line:
```bash
Failed to take screenshot on reject:     {}
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at elements(".logout") - isExisting.js:46:17
    at isExisting(".logout") - index.js:263:37
    at elementIdDisplayed("0.33832731039991915-1") - isVisible.js:71:55
```
The channel closed is because in the addAfterStep function of the reporter apparently it does think it has screenshots but the this.results[currentScenario.cid]._elements[currentScenario.uid] can be undefined and trying to access steps on undefined doesn't really work that well ;)

**Comment by wswebcreation** [comment]
Ahh, tnx for diving into it.

Care for a PR to fix it? I'm kinda stuffed the coming days

**Comment by Rob-Meijeren** [comment]
I will look into it on the weekend

**Comment by wswebcreation** [comment]
Thanks!

**Comment by Rob-Meijeren** [comment]
PR is made

**Comment by wswebcreation** [comment]
Release version[0.3.3](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/tree/v0.3.3)

Thanks for the PR and your work!
