### ISSUE TITLE
Is adding Text and Json to scenario possible?

### ISSUE THREAD

**Issue by PhilipSwiatczak** [wswebcreation/wdio-multiple-cucumber-html-reporter#18]
Hello @wswebcreation , 

Thank you for your outstanding work on this and other multiple-cucumber-html-reporters.

It appears whenever `this.attach` (cucumber World.attach) is used to append Text or JSON in a cucumber step, the addition gets **ignored/suppressed** by WDIO and subsequently also missing from your json output. 

Running naked cucumber from command line (no WDIO) with same dependencies produces desired entry in the cucumber json output:
```
            "embeddings": [
              {
                "data": "Session ID: xxxxxxx",
                "mime_type": "text/plain"
              }
            ]
```

example of failing embedding in a sample step:
```
Given(/^background prep$/, background);
async function background(): Promise<void> {
    await this.attach('Session ID:' + browser.sessionId);
}
```

**Environment:**
 - Node.js version: 8.12
 - NPM version: 6.4.1
 - webdriver.io version: ^4.14.1
 - wdio-cucumber-framework version: ^2.2.8
 - wdio-multiple-cucumber-html-reporter version: ^0.3.2

I've scoured forums looking for any clues but not a single thread exists mentioning text or json. There's nothing on WDIO api docs either (only screenshot capture) **Printing session ID, attaching network and console logs** could all be very usefully achieved this way as is the case in your other reporters. 

Please let me know if you are aware of this being an issue and/or any clues on tackling this. Thanks a lot! 
Best, Philip

**Comment by wswebcreation** [comment]
Hi @PhilipSwiatczak 

First of all thanks for the compliments. 

This module is only a translation from the Wdio reporter to a CucumberJS JSON file. The wdio-reporter 
doesn't use the original CucumberJS JSONFormatter which resulted in me _rebuilding_ the CucumberJS JSON file again. 
I need to dive into the `attach` event if I can find it in the wdio-reporter and translate it back to embeddings for CucumberJS, but if you already found it please feel free to create a PR for it 😉

**Comment by wswebcreation** [comment]
Hi @jacknjill02 

I didn't had time the last month, I still need to check this, hopefully next week

**Comment by wswebcreation** [comment]
This is now added in version `1.0.1`, see [here](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/releases/tag/1.0.1)
