### ISSUE TITLE
Execution End Time in the report

### ISSUE THREAD

**Issue by jacknjill02** [wswebcreation/wdio-multiple-cucumber-html-reporter#19]
While using customData how could I pass the exact "Execution End Time" in the reporterOptions since reporterOptions are provided in the wdio.config which is passed to the wdio launcher when tests are started.

```js
customData: {
    title: 'Run info',
    data: [
        {label: 'Project', value: 'Custom project'},
        {label: 'Release', value: '1.2.3'},
        {label: 'Cycle', value: 'B11221.34321'},
        {label: 'Execution Start Time', value: 'Nov 19th 2017, 02:31 PM EST'},
        {label: 'Execution End Time', value: 'Nov 19th 2017, 02:56 PM EST'}
    ]
}
```

I am using following versions.

 - Node.js version: 8.11.3
 - NPM version: 5.6.0
 - webdriver.io version: 4.10.2
 - wdio-cucumber-framework version: 2.2.8
 - wdio-multiple-cucumber-html-reporter version: 0.3.3

**Comment by wswebcreation** [comment]
Hi @jacknjill02 

Hmm, you are right, this needs to be removed because you can't. Care for a PR?

**Comment by dkpalmer** [comment]
@wswebcreation Are you suggesting a PR to remove from the docs, or to add support? If you have thoughts on how something like execution end time could be provided I'd be interested in looking into it.

**Comment by wswebcreation** [comment]
Hi @dkpalmer

This needs to be removed from the docs because currently we can't. Unless you think there is a way

**Comment by dkpalmer** [comment]
Poking around, it makes sense that you wouldn't be able to pass a separate property like endTime in after this way.

I still like the idea of being able to see some before/after timestamps as additional info for the report. I quickly hacked in some dates into `reporter.js` in `onStart` and `onEnd`. Are there any situations this wouldn't surface the correct information?

**Comment by wswebcreation** [comment]
Hi @dkpalmer 

I think this might be the place, I'm not 100% sure if this will work with parallel execution, but it might do the trick.

**Comment by dkpalmer** [comment]
@wswebcreation Can you share your thoughts why parallel execution might not work? So far the only parallelization I've tried is multiple simulators locally. Because the reporter knows when it is launched, and I _believe_ it knows when all executions are finished since the reporters finishes by aggregating all JSON, it should work? Or is there another aspect to parallelization that adds some edge cases?

**Comment by wswebcreation** [comment]
Hi @dkpalmer 

That's true. I you like you can create a PR for it. Please make it optional 😉 so people can turn it on and off if they like
