### ISSUE TITLE
Could you make this as standalone HTML file so that we can sent via mail

### ISSUE THREAD

**Issue by qburst-hari** [wswebcreation/wdio-multiple-cucumber-html-reporter#22]
The current report we wont be able to sent via mail because it has got dependency on json file.

**Describe the solution you'd like**
So is it possible to make the html as standalone so that all values come inside the reporter. So this report can be sent via mail.

**Describe alternatives you've considered**
I have used another report html-format-report which is a standalone one

**Comment by wswebcreation** [comment]
Hi @qburst-hari 

What do you exactly mean? The report that is generated contains all kinds of html pages and is completely standalone. Just zip it if you need to send it.
