### ISSUE TITLE
Please make metadata optional

### ISSUE THREAD

**Issue by sankalp-gupta** [wswebcreation/wdio-multiple-cucumber-html-reporter#23]
Hi,

Is it possible to remove metadata from the report, if not, can it be made optional?

**Comment by wswebcreation** [comment]
Hi @sankalp-gupta 

Currently it's created on the fly. Can you explain the use case why you should not want to show the data?

**Comment by sankalp-gupta** [comment]
Hi Wim,

In my project, these details are not needed so seniors asked me if it can be removed from the report.

**Comment by wswebcreation** [comment]
Hmm, we can make it optional, but that's also the power of this report.

I'll add it to my feature wishlist, unless you want to create a PR for it
