### ISSUE TITLE
Taking screenshot in afterscenario gets attached to next scenario

### ISSUE THREAD

**Issue by spujar** [wswebcreation/wdio-multiple-cucumber-html-reporter#26]
**Environment (please complete the following information):**
 - Node.js version:v10.13.0
 - NPM version: 6.4.1
 - webdriver.io version: 4.14.0
 - wdio-cucumber-framework version: ^2.2.8
 - wdio-multiple-cucumber-html-reporter version: ^0.3.2

**Config of webdriver.io and the reporter**
An example of how you configured the reporter in your webdriver.io config

```
afterScenario: function(scenario) {
    browser.deleteCookie();
    browser.saveScreenshot().then(function(stream) {
      var decodedImage = new Buffer(stream, 'base64').toString('binary');
      scenario.attach(decodedImage, 'image/png');
    });

    console.log('------------------------------------------------------');
    console.log('FINISHED SCENARIO NAME:' + scenario.name);
  },
```
**Describe the bug**
On failures or at the end of completion of scenario, we would like to take screenshot. when we do this, the screenshot doesn't get attached to the scenario that is completed, but instead to first step in next scenario

**To Reproduce**
Add the above code in afterscenario hook and have two tests. Make first test fail. On failure, the screenshot is getting attached to first step next scenario 

**Expected behavior**
It is expected to attach to current scenario on the step where it failed.

**Comment by wswebcreation** [comment]
Hi @spujar

Please use the the code as explained in the docs https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/blob/master/README.md#how-do-i-add-screenshots-to-the-report


Going to close this one because it's working based on this code
