### ISSUE TITLE
Get browsername and version from bodyvalue instead of metadata

### ISSUE THREAD

**Issue by siva1711** [wswebcreation/wdio-multiple-cucumber-html-reporter#29]
**Environment (please complete the following information):**
 - Node.js version: 10.13.0
 - NPM version: 6.4.1
 - webdriver.io version: 4.14.4
 - wdio-cucumber-framework version: 2.2.8
 - wdio-multiple-cucumber-html-reporter version: 1.0.2

**Config of webdriver.io and the reporter**
An example of how you configured the reporter in your webdriver.io config

**Describe the bug**
Browsername and version are now mandated from metadata in the latest version. Can we bring back the same logic as old version to get the browsername and version from body value if not from meta data.

**To Reproduce**
Run the test with metadata without browser.name and browser.version object in the metadata.

**Comment by wswebcreation** [comment]
@siva1711 

Can you please provide your config?

**Comment by siva1711** [comment]
> @siva1711
> 
> Can you please provide your config?

I am defining the common metadata for all types of browsers without providing browser.name and browser.version assuming these values will be fetched from body value. Here is my metadata configuration in the desired capabilities.
metadata:{
device: 'Windows',
    platform: {
        name: 'windows',
        version: 'Windows 10'
    }
}

**Comment by wswebcreation** [comment]
@siva1711

Thanks, I'll check it when I have time

**Comment by wswebcreation** [comment]
Hi @siva1711 

I've created a fix for this and published version [v1.0.3](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/releases/tag/v1.0.3). Can you please check if it works for you, make sure you removed you `package-lock.json` to get the latest version with this fix.

If it is fixed, please close the issue

**Comment by siva1711** [comment]
Hi Wim,

Thanks for your quick fix. It works fine now. I think you forgot to remove the console.log, ignore me if that is intentional.

Regards,
Siva

**Comment by wswebcreation** [comment]
Will remove it, thnx for the heads-up, will release a new version soon

**Comment by wswebcreation** [comment]
I released version `1.0.4` that doesn't have the logs. Thanks for mentioning this
