### ISSUE TITLE
openReportInBrowser: true does not open report in browser

### ISSUE THREAD

**Issue by FlippieCoetser** [wswebcreation/wdio-multiple-cucumber-html-reporter#5]
**Actual:**
Background:
Given `openReportInBrowser` is set to `true` in `wdio.conf.js`

Scenario:
When I run all cucumber tests
And a report is produced
Then the report is not opened in the browser

**Expected:**
Background:
Given `openReportInBrowser` is set to `true` in `wdio.conf.js`

Scenario:
When I run all cucumber tests
And a report is produced
Then the report should open in the browser

Platform: Windows 10

**Comment by FlippieCoetser** [comment]
@wswebcreation it looks like more of the settings applied in the wdio.conf.js does not work. `metaData` fails. `pageTitle`, `reportName` and `displayDuration` succeeds.

**Comment by wswebcreation** [comment]
Tnx for checking, I was to excited to release that I didn't gave myself time to create proper testcases. 

I'll dive into it an fix it a.s.a.p., unless you want to add a PR ;-)

**Comment by wswebcreation** [comment]
🤔 

```js
    reporterOptions: {
        htmlReporter: {
            jsonFolder: '.tmp/new/',
            reportFolder: '.tmp/multiple-cucumber-html-reporter/',
            displayDuration: true,
            openReportInBrowser: true,
            saveCollectedJSON: true,
            disableLog: true,
            pageTitle: 'pageTitle',
            reportName: 'reportName',
            pageFooter: '<div><h1>Custom footer</h1></div>',
            customData: {
                title: 'Run info',
                data: [
                    {label: 'Project', value: 'Custom project'},
                    {label: 'Release', value: '1.2.3'},
                    {label: 'Cycle', value: 'B11221.34321'},
                    {label: 'Execution Start Time', value: 'Nov 19th 2017, 02:31 PM EST'},
                    {label: 'Execution End Time', value: 'Nov 19th 2017, 02:56 PM EST'}
                ]
            }
        }
    },
```

Results in opening the browser and creating this report

![image](https://user-images.githubusercontent.com/11979740/43094770-2a7a114a-8eb4-11e8-9e62-2d0dd77edf0d.png)

The only thing I now see that doesn't work is `metadata`. Is there more that doesn't work?

**Comment by FlippieCoetser** [comment]
Metadata was the only other setting that did not work. I will do more testing and when I find something I will open a new ticket. Soon I will also have a Dev environment ready then I can help with PR.

**Comment by wswebcreation** [comment]
Ok, tnx, I think I need to remove the `metadata` options because all gets defaulted by this module already. Will check it later this week

**Comment by wswebcreation** [comment]
I've removed the metadata and released a new version. All options should now be working. I'm going to close it for now. If you see an other issue please let me know
